services:
  - type: web
    name: ai-caller-app
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: WEBHOOK_URL
        fromService: self
